spring:
  application:
    name: configserver
  # cloud:
  #   config:
  #     server:
  #       git:
  #         uri: https://github.com/AdityaRaj81/config-repo
  #         clone-on-start: true

  cloud:
    config:
      server:
        native:
          search-locations: C:\JavaLearn\config-repo
  profiles:
    active: native
  
server:
  port: 8888
